### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by SiamKreative** [ThemeAvenue/BetterOptin#13]
The roadmap for our plugin. Feel free to suggest new features here.

- [ ] Allow iframes, shortcodes, videos #14
- [ ] Scroll down to subscribe #7
- [ ] Ability to trigger popups on categories pages #16
